"""Generate src/Strings.cs: UI string map for translation (English source).

IDs: ui.* (hand list below), group.* (save-editor group names, used as-is),
field.* (humanized camelCase; proper nouns like Agnolia stay untouched so
translators keep them as-is). Translators: copy the en dict to a new locale
and register it via Lang.Add(name, dict); T(id) falls back to en, then id.
Usage: & "<save-editor>/venv/Scripts/python.exe" Utils/gen_strings.py
"""
import ast
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONSTS = Path(r"C:\Users\GLENN\Documents\git repos\Suzerain-Save-Editor\Utils\Consts.py")
tree = ast.parse(CONSTS.read_text(encoding="utf-8"))
ns = {}
for node in tree.body:
    if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
        try:
            ns[node.targets[0].id] = ast.literal_eval(node.value)
        except Exception:
            pass

UI = {
    "app.title": "BagOfTricks",
    "app.hotkey": "Ctrl+D",
    "menu.noCampaign": "no campaign loaded",
    "menu.loadHint": "load a campaign to enable cheats (browse, search, dump stay available)",
    "menu.sordland": "Sordland",
    "menu.rizia": "Rizia",
    "menu.settings": "Settings",
    "menu.language": "Language",
    "menu.experimental": "Experimental extras",
    "menu.experimentalOff": "Mined extras hidden — enable Experimental in Settings.",    "menu.search": "Search",
    "menu.maxMoney": "Max Money",
    "menu.maxResources": "Max Resources",
    "menu.dumpNow": "Dump all keys now (F9)",
    "menu.dumpNote": "Dump writes every catalog key with live values to UserData.",
    "menu.numberHint": "Number fields apply on Enter; +/- steps by 1.",
    "menu.more": "+{0} more (refine search)",
    "menu.modifies": "Modifies:",
    "menu.versionBy": "v{0} by {1}",
    "menu.on": "ON",
    "menu.off": "OFF",
    "menu.mix": "MIX",
    "menu.win": "WIN",
    "menu.lost": "LOST",
    "menu.err": "ERR",
    "menu.none": "—",
    "menu.tripped": "TRIPPED: ",
    "menu.caution": "Caution: ",
    "menu.extrasSordland": "Mined extras (Sordland)",
    "menu.extrasRizia": "Mined extras (Rizia)",
}


def humanize(field):
    s = re.sub(r"(?<!^)(?=[A-Z])", " ", field).replace("_", " ").strip()
    return s[:1].upper() + s[1:]


strings = dict(UI)
for sp in ("sordland", "rizia"):
    for group in ns["GROUP_SORDLAND" if sp == "sordland" else "GROUP_RIZIA"]:
        strings.setdefault(f"group.{group}", group)
        fmap = ns["FIELD_MAP_SORDLAND" if sp == "sordland" else "FIELD_MAP_RIZIA"]
        for f in ns["GROUP_SORDLAND" if sp == "sordland" else "GROUP_RIZIA"][group]:
            strings.setdefault(f"field.{f}", humanize(f))

lines = ["namespace BagOfTricks;",
         "// Generated by Utils/gen_strings.py — do not hand-edit.",
         "// Translators: proper nouns (countries, cities, people) stay as-is.",
         "internal static class Strings",
         "{",
         "    internal static readonly System.Collections.Generic.Dictionary<string,string> en=new System.Collections.Generic.Dictionary<string,string>()",
         "    {"]
for k in sorted(strings):
    v = strings[k].replace("\\", "\\\\").replace('"', "'").replace("\n", " ")
    lines.append(f'        {{"{k}", "{v}"}},')
lines += ["    };",
          "    internal static readonly System.Collections.Generic.Dictionary<string,string> zhHans=new System.Collections.Generic.Dictionary<string,string>()",
          "    {"]
zh = json.loads((REPO / "Utils" / "strings_zh-Hans.json").read_text(encoding="utf-8"))
for k in sorted(zh):
    v = zh[k].replace("\\", "\\\\").replace('"', "'").replace("\n", " ")
    lines.append(f'        {{"{k}", "{v}"}},')
lines += ["    };",
          '    static Strings(){langs["zh-Hans"]=zhHans;}',
          "    internal static readonly System.Collections.Generic.Dictionary<string,System.Collections.Generic.Dictionary<string,string>> langs=new System.Collections.Generic.Dictionary<string,System.Collections.Generic.Dictionary<string,string>>();",
          '    internal static string current="en";',
          "    internal static void Add(string name,System.Collections.Generic.Dictionary<string,string> dict){langs[name]=dict;}",
          "    internal static string T(string id)",
          "    {",
          "        string v=null;",
          "        System.Collections.Generic.Dictionary<string,string> d=null;",
          "        if(current!=\"en\"&&langs.TryGetValue(current,out d)&&d.TryGetValue(id,out v))return v;",
          "        if(en.TryGetValue(id,out v))return v;",
          "        return id;",
          "    }",
          "}"]
(REPO / "src" / "Strings.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote Strings.cs: {len(strings)} en + {len(zh)} zh-Hans strings")
