"""Generate src/Warnings.cs: per-key gate list + hand-curated danger rules.

Gates come from dialogue conditions (conversation_refs.json) for mapped keys:
each {op, value, turn, conv}. Turn parsed from conversation path
(Sordland/Turn05/.. or Rizia/Turn 10/..); 0 = always relevant.
DANGER rules are hand-written from evidence (see notes.md timing model).
Usage: & "<save-editor>/venv/Scripts/python.exe" Utils/gen_warnings.py
"""
import ast
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
MINING = REPO / "GameDump" / "3.1.0.1.175" / "mining"
CONSTS = Path(r"C:\Users\GLENN\Documents\git repos\Suzerain-Save-Editor\Utils\Consts.py")
tree = ast.parse(CONSTS.read_text(encoding="utf-8"))
ns = {}
for node in tree.body:
    if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
        try:
            ns[node.targets[0].id] = ast.literal_eval(node.value)
        except Exception:
            pass
maps = set(ns["FIELD_MAP_SORDLAND"].values()) | set(ns["FIELD_MAP_RIZIA"].values())
REFS = json.loads((MINING / "conversation_refs.json").read_text(encoding="utf-8"))
CMP_RE = re.compile(r'Variable\["([^"]+)"\]\s*(>=|<=|==|~=|>|<)\s*(-?\d+(?:\.\d+)?)')
TURN_RE = re.compile(r"[Tt]urn\s*0?(\d+)")

DANGER = {
    "BaseGame.BlackTuesdayHappened": "Black Tuesday crash branch (Turn05+ military/immigration)",
    "BaseGame.SuperpowerTradeWarHappened": "Superpower trade-war branch",
    "BaseGame.Situation_Economy_GlobalTradeWar": "Global trade-war branch",
    "BaseGame.Situation_Order_Corruption": "Corruption crisis branch",
}

out = {}
for key in sorted(maps):
    gates = []
    for h in REFS.get(key, []):
        if h["kind"] != "cond":
            continue
        m = TURN_RE.search(h["conv"] or "")
        turn = int(m.group(1)) if m else 0
        for c in CMP_RE.finditer(h["snippet"]):
            if c.group(1) == key:
                gates.append((c.group(2), c.group(3), turn, h["conv"]))
    seen = set()
    uniq = [g for g in gates if not (g in seen or seen.add(g))]
    if uniq or key in DANGER:
        out[key] = {"gates": [{"op": o, "val": v, "turn": t, "conv": c} for o, v, t, c in uniq[:12]],
                    "danger": DANGER.get(key, "")}

lines = ["namespace BagOfTricks;",
         "// Generated by Utils/gen_warnings.py — do not hand-edit.",
         "internal sealed class Gate",
         "{",
         "    internal string op=\"\";",
         "    internal string val=\"\";",
         "    internal int turn;",
         "    internal string conv=\"\";",
         "}",
         "internal sealed class WarnEntry",
         "{",
         "    internal string key=\"\";",
         "    internal string danger=\"\";",
         "    internal Gate[] gates=new Gate[0];",
         "}",
         "internal static class Warnings",
         "{",
         "    internal static readonly WarnEntry[] All=new WarnEntry[]",
         "    {"]
for key, e in out.items():
    gs = ",".join('new Gate{op="%s",val="%s",turn=%d,conv="%s"}' % (g["op"], g["val"], g["turn"], g["conv"].replace('"', "'")) for g in e["gates"])
    dg = e["danger"].replace('"', "'")
    lines.append(f'        new WarnEntry{{key="{key}",danger="{dg}",gates=new Gate[]{{{gs}}}}},')
lines += ["    };",
          "    internal static WarnEntry Find(string key)",
          "{",
          "        foreach(var e in All)if(e.key==key)return e;",
          "        return null;",
          "    }",
          "}"]
(REPO / "src" / "Warnings.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote Warnings.cs: {len(out)} keys")
