"""Generate src/Keys.cs: every known variable key (maps + mined extras).

Types come from mining/universe.json (bool keys render as toggles, rest as
int steppers in the F10 menu). Run Utils/mine_saves.py at least once first.
"""
import ast
import json
from pathlib import Path

REPO = Path(r"C:\Users\GLENN\Documents\git repos\Suzerain-BagOfTricks")
CONSTS = Path(r"C:\Users\GLENN\Documents\git repos\Suzerain-Save-Editor\Utils\Consts.py")

tree = ast.parse(CONSTS.read_text(encoding="utf-8"))
ns = {}
for node in tree.body:
    if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
        try:
            ns[node.targets[0].id] = ast.literal_eval(node.value)
        except Exception:
            pass
keys = set(ns["FIELD_MAP_SORDLAND"].values()) | set(ns["FIELD_MAP_RIZIA"].values())
extras = json.loads((REPO / "Utils" / "api_extras.json").read_text(encoding="utf-8"))
for sec in extras["sections"]:
    for row in sec["rows"]:
        keys.add(row[0])
uni = json.loads((REPO / "GameDump" / "3.1.0.1.175" / "mining" / "universe.json").read_text(encoding="utf-8"))

def is_bool(k):
    t = uni.get(k, {}).get("types", [])
    return t == ["bool"]

lines = ["namespace BagOfTricks;",
         "// Generated by Utils/gen_keys.py — do not hand-edit. Re-run after API.md regen.",
         "internal readonly struct Entry",
         "{",
         "    internal readonly string name;",
         "    internal readonly bool isBool;",
         "    internal Entry(string n,bool b){name=n;isBool=b;}",
         "}",
         "internal static class Keys",
         "{",
         "    internal static readonly string[] All=new string[]",
         "    {"]
for k in sorted(keys):
    lines.append(f'        "{k}",')
lines += ["    };",
          "    internal static readonly Entry[] Typed=new Entry[]",
          "    {"]
for k in sorted(keys):
    lines.append(f'        new Entry("{k}",{"true" if is_bool(k) else "false"}),')
lines += ["    };", "}"]
(REPO / "src" / "Keys.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote Keys.cs: {len(keys)} keys")
