"""Generate src/MenuGroups.cs: save-editor group layout + composite option data.

Reads Utils/Consts.py (STORY_PACK groups, FIELD_MAPs — same order as the
save-editor UI), universe types for widget kinds, and Utils/groups.json
names for pair/lever rows. Emits per-pack ordered groups with rows of
kind int/bool/group, plus CompositeDefs for enum composites ported from
Models/Sordland.py (AND-pairs etc. already live in Groups.cs).
Unresolvable fields (wehlenAlliance) are skipped with a report.
Usage: & "<save-editor>/venv/Scripts/python.exe" Utils/gen_menu.py
"""
import ast
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONSTS = Path(r"C:\Users\GLENN\Documents\git repos\Suzerain-Save-Editor\Utils\Consts.py")
tree = ast.parse(CONSTS.read_text(encoding="utf-8"))
ns = {}
for node in tree.body:
    if isinstance(node, ast.Assign) and len(node.targets) == 1 and isinstance(node.targets[0], ast.Name):
        try:
            ns[node.targets[0].id] = ast.literal_eval(node.value)
        except Exception:
            pass
MAPS = {**ns["FIELD_MAP_SORDLAND"], **ns["FIELD_MAP_RIZIA"]}
GROUPS = {"sordland": {"field_map": ns["FIELD_MAP_SORDLAND"], "group": ns["GROUP_SORDLAND"]},
          "rizia": {"field_map": ns["FIELD_MAP_RIZIA"], "group": ns["GROUP_RIZIA"]}}
TOG = {g["name"] for g in json.loads((REPO / "Utils" / "groups.json").read_text(encoding="utf-8"))["groups"]}
UNI = json.loads((REPO / "GameDump" / "3.1.0.1.175" / "mining" / "universe.json").read_text(encoding="utf-8"))

COMPOSITES = {
    "employment": {"GOOD": ["_highEmployment"], "BAD": ["_unemploymentCrisis"]},
    "trade": {"GOOD": ["_increasedTrade"], "BAD": ["_decreasedTrade"]},
    "tax": {"GOOD": ["_taxEfficientEconomy"], "MID": ["_taxAvoidance"], "BAD": ["_taxEvasion"]},
    "transportation": {"GOOD": ["_improvedTransportation"], "BAD": ["_weakTransportation"]},
    "tourism": {"GOOD": ["_tourismBooming"], "MID": ["_tourismAverage"], "BAD": ["_tourismDeclining"]},
    "situationAgnland": {"GOOD": ["_agnlandMajorFishExport"], "MID": ["_agnlandEconomicStabilisation"], "BAD": ["_agnlandLackInvestment"]},
    "situationBergia": {"GOOD": ["_bergiaMajorAgriculturalZone"], "MID": ["_bergiaEconomicStabilisation"], "BAD": ["_bergiaEconomicDownturn"]},
    "situationGruni": {"GOOD": ["_gruniLightTowerRegion"], "MID": ["_gruniMaintainingGrowth"], "BAD": ["_gruniLaggingBehind"]},
    "situationLorren": {"GOOD": ["_lorrenProductionAndTradeCenter"], "MID": ["_lorrenEconomicStabilisation"], "BAD": ["_lorrenRustBelt"]},
    "ewaldOpinion": {"DISCONTENT": ["_ewaldDiscontent"], "NEUTRAL": ["_ewaldNeutral"], "FRIENDLY": ["_ewaldFriendly"]},
    "partyElectionResult": {"WON": ["_partyElectionWon"], "LOST": ["_partyElectionLost"], "NEWPARTY": ["_partyElectionNewParty"]},
    "sordishRadioTVCouncilStatus": {"CONTROLLED": ["_sordishRadioTVCouncil", "_sordishRadioTVCouncilControlled"], "INDEPENDENT": ["_sordishRadioTVCouncil", "_sordishRadioTVCouncilIndependent"]},
    "operationBearTrap": {"MID": ["_wehlenDefendBorder"], "HIGH": ["_wehlenJointOperation"]},
    "courtStatus": {"BAD": ["_courtBacklog"], "GOOD": ["_efficientJusticeSystem"]},
    "womenRights": {"BAD": ["_limitedWomenRights"], "MID": ["_averageWomenRights"], "GOOD": ["_excellentWomenRights"]},
    "corruption": {"BAD": ["_corruption"], "GOOD": ["_corruptionTackled"]},
    "crime": {"BAD": ["_organisedCrime"], "GOOD": ["_organisedCrimeContained"]},
    "vesordRumbergNavy": {"BAD": ["_vesordRumburgNavyInferior"], "GOOD": ["_vesordRumburgNavySuperior"]},
}

q = lambda s: '"%s"' % s.replace('"', "'")
lines = ["namespace BagOfTricks;",
         "// Generated by Utils/gen_menu.py — do not hand-edit.",
         "internal sealed class MenuRow",
         "{",
         "    internal string label=\"\";",
         "    internal string kind=\"\";",
         "    internal string key=\"\";",
         "    internal string group=\"\";",
         "}",
         "internal sealed class MenuGroup",
         "{",
         "    internal string pack=\"\";",
         "    internal string name=\"\";",
         "    internal MenuRow[] rows=new MenuRow[0];",
         "}",
         "internal static class MenuData",
         "{",
         "    internal static readonly GroupDef[] Composites=new GroupDef[]",
         "    {"]
for name, opts in COMPOSITES.items():
    onames = ",".join(q(o) for o in opts)
    okeys = ",".join("new string[]{" + ",".join(q(MAPS[m]) for m in ks) + "}" for ks in opts.values())
    lines.append(f'        new GroupDef{{name="{name}",kind="composite",optNames=new string[]{{{onames}}},optKeys=new string[][]{{{okeys}}}}},')
lines += ["    };",
          "    internal static readonly MenuGroup[] Groups=new MenuGroup[]",
          "    {"]
skipped = []
nrows = 0
for pack, spec in GROUPS.items():
    for group, fields in spec["group"].items():
        rows = []
        for f in fields:
            if f in TOG:
                rows.append((f, "group", "", f))
            elif f in MAPS or "_" + f in MAPS:
                key = MAPS.get(f, MAPS.get("_" + f))
                kind = "bool" if UNI.get(key, {}).get("types", []) == ["bool"] else "int"
                rows.append((f, kind, key, ""))
            elif f in COMPOSITES:
                rows.append((f, "group", "", f))
            else:
                skipped.append((pack, group, f))
        rstr = ",".join('new MenuRow{label="%s",kind="%s",key="%s",group="%s"}' % (r[0], r[1], r[2], r[3]) for r in rows)
        lines.append(f'        new MenuGroup{{pack="{pack}",name="{group}",rows=new MenuRow[]{{{rstr}}}}},')
        nrows += len(rows)
lines += ["    };",
          "    internal static readonly string[] Mates=new string[]",
          "    {"]
mates = {}
def add_mates(keys):
    for k in keys:
        mates.setdefault(k, set()).update(keys)
TOGFULL = json.loads((REPO / "Utils" / "groups.json").read_text(encoding="utf-8"))["groups"]
for g in TOGFULL:
    mem = list(g.get("members", []))
    for opts in g.get("options", {}).values():
        mem += opts
    add_mates(mem)
for opts in COMPOSITES.values():
    add_mates([MAPS[m] for ks in [opts[o] for o in opts] for m in ks])
for k in sorted(mates):
    lines.append(f'        "{k}={"|".join(sorted(mates[k]))}",')
lines += ["    };", "}"]
(REPO / "src" / "MenuGroups.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote MenuGroups.cs: {nrows} rows, skipped {len(skipped)}")
for s in skipped:
    print(f"  SKIP {s}")
