"""Generate src/Groups.cs from Utils/groups.json (modify-together widgets data).

Usage: & "<save-editor>/venv/Scripts/python.exe" Utils/gen_groups.py
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
groups = json.loads((REPO / "Utils" / "groups.json").read_text(encoding="utf-8"))["groups"]

lines = ["namespace BagOfTricks;",
         "// Generated by Utils/gen_groups.py — do not hand-edit.",
         "internal sealed class GroupDef",
         "{",
         "    internal string name=\"\";",
         "    internal string kind=\"\";",
         "    internal string[] members=new string[0];",
         "    internal string[] optNames=new string[0];",
         "    internal string[][] optKeys=new string[0][];",
         "}",
         "internal static class Groups",
         "{",
         "    internal static readonly GroupDef[] All=new GroupDef[]",
         "    {"]
for g in groups:
    if "options" in g:
        names = ",".join(f'"{o}"' for o in g["options"])
        keys = ",".join("new string[]{" + ",".join(f'"{kk}"' for kk in v) + "}" for v in g["options"].values())
        lines.append(f'        new GroupDef{{name="{g["name"]}",kind="{g["kind"]}",optNames=new string[]{{{names}}},optKeys=new string[][]{{{keys}}}}},')
    else:
        mem = ",".join(f'"{k}"' for k in g["members"])
        lines.append(f'        new GroupDef{{name="{g["name"]}",kind="{g["kind"]}",members=new string[]{{{mem}}}}},')
lines += ["    };", "}"]
(REPO / "src" / "Groups.cs").write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"wrote Groups.cs: {len(groups)} groups")
