namespace BagOfTricks;
// Generated by Utils/gen_groups.py — do not hand-edit.
internal sealed class GroupDef
{
    internal string name="";
    internal string kind="";
    internal string[] members=new string[0];
    internal string[] optNames=new string[0];
    internal string[][] optKeys=new string[0][];
}
internal static class Groups
{
    internal static readonly GroupDef[] All=new GroupDef[]
    {
        new GroupDef{name="blackTuesday",kind="and",members=new string[]{"BaseGame.BlackTuesdayHappened","BaseGame.Situation_Economy_MarketsCrash"}},
        new GroupDef{name="superpowerTradeWar",kind="and",members=new string[]{"BaseGame.SuperpowerTradeWarHappened","BaseGame.Situation_Economy_GlobalTradeWar"}},
        new GroupDef{name="deanaLoved",kind="and",members=new string[]{"BaseGame.Relations_Deana_Loved","BaseGame.Relations_Deana_Opinion"}},
        new GroupDef{name="agnoliaTradeDeal",kind="and",members=new string[]{"BaseGame.Agnolia_TradeDeal","BaseGame.Policy_Diplomacy_Agnolia_Trade"}},
        new GroupDef{name="agnoliaAlliance",kind="and",members=new string[]{"BaseGame.Agnolia_Alliance","BaseGame.Policy_Diplomacy_Agnolia_Alliance"}},
        new GroupDef{name="wehlenTradeDeal",kind="and",members=new string[]{"BaseGame.Wehlen_TradeDeal","BaseGame.Policy_Diplomacy_Wehlen_Trade"}},
        new GroupDef{name="lespiaAlliance",kind="and",members=new string[]{"BaseGame.Lespia_Alliance","BaseGame.Policy_Diplomacy_Lespia_Alliance"}},
        new GroupDef{name="valgslandAlliance",kind="and",members=new string[]{"BaseGame.Valgsland_Alliance","BaseGame.Policy_Diplomacy_Valgsland_Alliance"}},
        new GroupDef{name="ATO",kind="and",members=new string[]{"BaseGame.Policy_Diplomacy_ATO","BaseGame.Policy_Economy_ATOArea"}},
        new GroupDef{name="CSP",kind="and",members=new string[]{"BaseGame.Policy_Diplomacy_CSP","BaseGame.Policy_Economy_CSPArea"}},
        new GroupDef{name="modernisedArmy",kind="and",members=new string[]{"BaseGame.Situation_Military_ModernisedArmy","BaseGame.Turn06_SnO_Modernisation_Army"}},
        new GroupDef{name="expandedArmy",kind="and",members=new string[]{"BaseGame.Situation_Military_ExpandedArmy","BaseGame.Turn06_SnO_Expansion_Army"}},
        new GroupDef{name="modernisedNavy",kind="and",members=new string[]{"BaseGame.Situation_Military_ModernisedNavy","BaseGame.Turn06_SnO_Modernisation_Navy"}},
        new GroupDef{name="expandedNavy",kind="and",members=new string[]{"BaseGame.Situation_Military_ExpandedNavy","BaseGame.Turn06_SnO_Expansion_Navy"}},
        new GroupDef{name="modernisedAirForce",kind="and",members=new string[]{"BaseGame.Situation_Military_ModernisedAirForce","BaseGame.Turn06_SnO_Modernisation_Airforce"}},
        new GroupDef{name="expandedAirForce",kind="and",members=new string[]{"BaseGame.Situation_Military_ExpandedAirForce","BaseGame.Turn06_SnO_Expansion_Airforce"}},
        new GroupDef{name="rumburgWarWin",kind="inverse",members=new string[]{"GameCondition.Turn11_SnO_RumburgWarWin","GameCondition.Turn11_SnO_RumburgWarLost"}},
        new GroupDef{name="employment",kind="exclusive",optNames=new string[]{"BAD","GOOD"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_UnemploymentCrisis"},new string[]{"BaseGame.Situation_Economy_HighEmployment"}}},
        new GroupDef{name="trade",kind="exclusive",optNames=new string[]{"BAD","GOOD"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_DecreasedTrade"},new string[]{"BaseGame.Situation_Economy_IncreasedTrade"}}},
        new GroupDef{name="tax",kind="exclusive",optNames=new string[]{"BAD","GOOD","MID"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_TaxEvasion"},new string[]{"BaseGame.Situation_Economy_TaxEfficientEconomy"},new string[]{"BaseGame.Situation_Economy_TaxAvoidance"}}},
        new GroupDef{name="transportation",kind="exclusive",optNames=new string[]{"BAD","GOOD"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_WeakTransportation"},new string[]{"BaseGame.Situation_Economy_ImprovedTransportation"}}},
        new GroupDef{name="tourism",kind="exclusive",optNames=new string[]{"BAD","GOOD","MID"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_Tourism_Declining"},new string[]{"BaseGame.Situation_Economy_Tourism_Booming"},new string[]{"BaseGame.Situation_Economy_Tourism_Average"}}},
        new GroupDef{name="situationAgnland",kind="exclusive",optNames=new string[]{"BAD","GOOD","MID"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_Agnland_LackInvestment"},new string[]{"BaseGame.Situation_Economy_Agnland_MajorFishExport"},new string[]{"BaseGame.Situation_Economy_Agnland_EconomicStabilisation"}}},
        new GroupDef{name="situationBergia",kind="exclusive",optNames=new string[]{"BAD","GOOD","MID"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_Bergia_EconomicDownturn"},new string[]{"BaseGame.Situation_Economy_Bergia_MajorAgriculturalZone"},new string[]{"BaseGame.Situation_Economy_Bergia_EconomicStabilisation"}}},
        new GroupDef{name="situationGruni",kind="exclusive",optNames=new string[]{"BAD","GOOD","MID"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_Gruni_LaggingBehind"},new string[]{"BaseGame.Situation_Economy_Gruni_LightTowerRegion"},new string[]{"BaseGame.Situation_Economy_Gruni_MaintainingGrowth"}}},
        new GroupDef{name="situationLorren",kind="exclusive",optNames=new string[]{"BAD","GOOD","MID"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Economy_Lorren_RustBelt"},new string[]{"BaseGame.Situation_Economy_Lorren_ProductionAndTradeCenter"},new string[]{"BaseGame.Situation_Economy_Lorren_EconomicStabilisation"}}},
        new GroupDef{name="ewaldOpinion",kind="exclusive",optNames=new string[]{"DISCONTENT","FRIENDLY","NEUTRAL","NONE"},optKeys=new string[][]{new string[]{"BaseGame.Relations_Ewald_Discontent"},new string[]{"BaseGame.Relations_Ewald_Friendly"},new string[]{"BaseGame.Relations_Ewald_Neutral"},new string[]{}}},
        new GroupDef{name="partyElectionResult",kind="exclusive",optNames=new string[]{"LOST","NEWPARTY","NONE","WON"},optKeys=new string[][]{new string[]{"BaseGame.Turn10_PartyCongress_Lost"},new string[]{"BaseGame.Turn10_PartyCongress_FormNewParty"},new string[]{},new string[]{"BaseGame.Turn10_PartyCongress_Won"}}},
        new GroupDef{name="sordishRadioTVCouncilStatus",kind="exclusive",optNames=new string[]{"CONTROLLED","INDEPENDENT","NONE"},optKeys=new string[][]{new string[]{"BaseGame.Reform_PresiPower_Weak_SordishRadioTVCouncil","BaseGame.Reform_PresiPower_Weak_SordishRadioTVCouncil_Controlled"},new string[]{"BaseGame.Reform_PresiPower_Weak_SordishRadioTVCouncil","BaseGame.Reform_PresiPower_Weak_SordishRadioTVCouncil_Independent"},new string[]{}}},
        new GroupDef{name="operationBearTrap",kind="exclusive",optNames=new string[]{"HIGH","MID","NONE"},optKeys=new string[][]{new string[]{"BaseGame.Wehlen_JointOperation"},new string[]{"BaseGame.Wehlen_DefendBorder"},new string[]{}}},
        new GroupDef{name="courtStatus",kind="exclusive",optNames=new string[]{"BAD","GOOD"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Law_CourtBacklog"},new string[]{"BaseGame.Situation_Law_EfficientJusticeSystem"}}},
        new GroupDef{name="womenRights",kind="exclusive",optNames=new string[]{"BAD","GOOD","MID"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Law_LimitedWomenRights"},new string[]{"BaseGame.Situation_Law_ExcellentWomenRights"},new string[]{"BaseGame.Situation_Law_AverageWomenRights"}}},
        new GroupDef{name="corruption",kind="exclusive",optNames=new string[]{"BAD","GOOD"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Order_Corruption"},new string[]{"BaseGame.Situation_Order_CorruptionTackled"}}},
        new GroupDef{name="crime",kind="exclusive",optNames=new string[]{"BAD","GOOD"},optKeys=new string[][]{new string[]{"BaseGame.Situation_Order_OrganisedCrime"},new string[]{"BaseGame.Situation_Order_OrganisedCrimeContained"}}},
        new GroupDef{name="vesordRumbergNavy",kind="exclusive",optNames=new string[]{"BAD","GOOD"},optKeys=new string[][]{new string[]{"BaseGameSupport.Report_Turn10_Vesord_RumburgNavyInferior"},new string[]{"BaseGameSupport.Report_Turn10_Vesord_RumburgNavySuperior"}}},
        new GroupDef{name="authorityModifiersTotal",kind="compensating",members=new string[]{"RiziaDLC.Resources_AuthorityModifiersTotal","RiziaDLC.Authority_Modifier_BaseMonarchRomus"}},
        new GroupDef{name="budgetModifiersTotal",kind="compensating",members=new string[]{"RiziaDLC.Resources_BudgetModifiersTotal","RiziaDLC.Budget_Modifier_RizianGoldIndustry"}},
        new GroupDef{name="energyModifiersTotal",kind="compensating",members=new string[]{"RiziaDLC.Resources_EnergyModifiersTotal","RiziaDLC.Energy_Modifier_BaseEnergy"}},
    };
}
